# Generated by Django 6.0.2 on 2026-02-22 22:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('source', models.CharField(choices=[('camera', 'Cámara'), ('upload', 'Subida')], default='upload', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('results_count', models.IntegerField(default=0)),
                ('searched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
